# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imag_Label = QtWidgets.QLabel(self.centralwidget)
        self.imag_Label.setGeometry(QtCore.QRect(14, 15, 771, 461))
        self.imag_Label.setText("")
        self.imag_Label.setPixmap(QtGui.QPixmap("../../../../../../../Users/91755/OneDrive/Pictures/DP/Comp.jpg"))
        self.imag_Label.setScaledContents(True)
        self.imag_Label.setObjectName("imag_Label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 480, 361, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 480, 361, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "blue"))
        self.pushButton_2.setText(_translate("MainWindow", "red"))

        self.pushButton.clicked.connect(self.chngeImage2)
        self.pushButton_2.clicked.connect(self.chngeImage1)

    def chngeImage1(self):
        self.imag_Label.setPixmap(QtGui.QPixmap("../../../../../../../Users/91755/OneDrive/Pictures/DP/Computer.jpg"))
    def chngeImage2(self):
        self.imag_Label.setPixmap(QtGui.QPixmap("../../../../../../../Users/91755/OneDrive/Pictures/DP/Comp.jpg"))
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
