# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createacc.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 620)
        Dialog.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(180, 50, 181, 61))
        self.label.setStyleSheet("font: 28pt \"MS Shell Dlg 2\"; color: rgb(243, 243, 243)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 170, 141, 61))
        self.label_2.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 127);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 270, 141, 61))
        self.label_3.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 127);")
        self.label_3.setObjectName("label_3")
        self.email = QtWidgets.QLineEdit(Dialog)
        self.email.setGeometry(QtCore.QRect(220, 180, 211, 41))
        self.email.setObjectName("email")
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(220, 280, 211, 41))
        self.password.setObjectName("password")
        self.confirmacc = QtWidgets.QPushButton(Dialog)
        self.confirmacc.setGeometry(QtCore.QRect(300, 450, 141, 41))
        self.confirmacc.setStyleSheet("background-color:rgb(167, 168, 167); font-size:14px")
        self.confirmacc.setObjectName("confirmacc")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 360, 171, 61))
        self.label_4.setStyleSheet("font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 127);")
        self.label_4.setObjectName("label_4")
        self.confirmpass = QtWidgets.QLineEdit(Dialog)
        self.confirmpass.setGeometry(QtCore.QRect(220, 370, 211, 41))
        self.confirmpass.setObjectName("confirmpass")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Sign up"))
        self.label_2.setText(_translate("Dialog", "Email"))
        self.label_3.setText(_translate("Dialog", "Password"))
        self.confirmacc.setText(_translate("Dialog", "Confirm"))
        self.label_4.setText(_translate("Dialog", "Confirm Pass"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
